disabled_rules:
# コードの記載のない改行を許可したい
- trailing_whitespace
# ネスト1つで怒られるのでDisableにしたい
- nesting

included:
  - Source
  - Tests
excluded:
  - Tests/SwiftLintFrameworkTests/Resources
  - Pods/
  - Podfile
  - Podfile.lock
opt_in_rules:
  - empty_count
  - file_header
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

line_length: 300
number_separator:
  minimum_length: 5

# 変数名の長さのMAXとMINを変更
variable_name:
  max_length:
    warning: 60
    error: 80
  min_length:
    warning: 1
    error: 0
